import streamlit as st

# Karena lo pake [general], dia jadi 'parent' dictionary
google_key = st.secrets["general"]["GOOGLE_API_KEY"]

# Sama juga buat supabase
supa_url = st.secrets["supabase"]["URL"]
supa_key = st.secrets["supabase"]["KEY"]

# Test print (Jangan print key aslinya di app production!)
print(f"Connecting to Supabase at: {supa_url}")
