# .streamlit/secrets.toml

[general]
GOOGLE_API_KEY = "AIzaSyB3psg0LdWeDEhOz_1pwiZ0MIW6E_5CBLg"  # Key Gemini kamu yang lama

[supabase]
URL = "https://ojdokrtjfunmlaqkskau.supabase.co"
KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qZG9rcnRqZnVubWxhcWtza2F1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAzNjk2ODgsImV4cCI6MjA4NTk0NTY4OH0.NY0NqrKfTSLYtEckatYjpkRkR2ThzvqAvCv4dUMSGB4"  # Key anon public kamu
